export const NavMenu = [
    {
        id:1,
        name:'About Us',
        path:'AboutUs',
    },
    {
        id:2,
        name:'Women',
        path:'women',
    },
    {
        id:3,
        name:'Men',
        path:'men',
    },
    {
        id:4,
        name:'Beauty',
        path:'beauty',
    },
    {
        id:5,
        name:'Accessories',
        path:'Accessories',
    },
    {
        id:6,
        name:'Blog',
        path:'blog',
    },
    {
        id:7,
        name:'Contact',
        path:'contact',
    },
]
